server:
  port: 5000


## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/poll?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: init
    # Initialize the datasource with available DDL and DML scripts
    initialization-mode: always


## Hibernate Properties

# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

## Hibernate Logging
#logging:
#  level:
#    root: DEBUG
#
#    org:
#      hibernate:
#        SQL: DEBUG


app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000
